version: '3'

services:
  mysql-backup:
    build: .
    container_name: mysql-backup
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - ./config:/app/config
      - ./backups:/app/backups
    restart: unless-stopped
