version: '3'

services:
  mysql-backup:
    build: .
    container_name: mysql-backup
    labels:
      - "author=Maik Bohrmann"
      - "repository=https://github.com/meddatzk/mysql-backup"
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - ./config:/app/config
      - ./backups:/app/backups
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN # Erforderlich für das Mounten von SMB-Shares
    security_opt:
      - apparmor:unconfined # Deaktiviert AppArmor-Einschränkungen
